/// <reference types="Cypress" />

import '../../../support/commands'

describe('Backoffice Steps - Questions', function () {
  beforeEach(() => {
    this.fixtures = Cypress.env('fixtures');
    cy.bo_login(
      this.fixtures.bo_user.email,
      this.fixtures.bo_user.password,
      this.fixtures.bo_user.permission
    )
  })

  it('question filter by subject', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get('.q-mb-xl > :nth-child(1) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.subject)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.subject)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Matéria/Assunto:' + this.fixtures.question.subject)
  })

  it('question filter by organizer', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(2) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.organizer)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.organizer)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Banca:' + this.fixtures.question.organizer)
  })

  it('question filter by institution', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(3) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type('BB')
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.institution)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Orgão/Instituição:' + this.fixtures.question.institution)
  })

  it('question filter by area', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(4) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.area)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.area)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Área:' + this.fixtures.question.area)
  })

  it('question filter by office', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(5) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.office)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.office)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Cargo:' + this.fixtures.question.office)
  })

  it('question filter by formation', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(6) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.formation)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.formation)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Escolaridade:' + this.fixtures.question.formation)
  })

  it('question filter by year', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(7) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.year)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.year)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Ano:' + this.fixtures.question.year)
  })

  it('question filter by formation area', () => {
    cy.visit(Cypress.env('bo_questions') + '/#/questoes/listagem')
    cy.url()
      .should('include', '/#/questoes/listagem')
    cy.get('.q-btn')
      .contains('Adicionar filtros')
      .click()
    cy.get(':nth-child(8) > .q-field > .q-field__inner > .q-field__control > .q-field__control-container')
      .type(this.fixtures.question.formation_area)
      .wait(1000)
      .type(' ')
    cy.get('.q-virtual-scroll__content')
      .contains(this.fixtures.question.formation_area)
      .last()
      .click()
    cy.get('.fixed-bottom > .q-btn')
      .contains('Adicionar')
      .click({ force: true })
    cy.get(':nth-child(2) > .q-chip')
      .contains('Formação específica:' + this.fixtures.question.formation_area)
  })
})